# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6b5b3215d54e81e7b2a36e2990a48b1f8e72ad6b81b14036d2cf5cf7382737a3db7a970704d3346b1fa29940a628611577623c234f60e052bf71a5791da8e43

test:
  secret_key_base: 8bb2dd1546123b716c952b3ff8f68eb6a7512fbe117c310fd2cb849650aaa93ee14853f0ca1730c9afa03900b886b1ee374f8f8cf111b8f6c38f8e7d5eb92f87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
